### ISSUE TITLE
Module auto completion in Company_Module.xml depends

### ISSUE THREAD

**Issue by Schrank** [enriquepiatti/Magicento#106]
Given this module.xml:

```
<?xml version="1.0"?>
<config>
    <modules>
        <Company_Module>
            <active>true</active>
            <codePool>local</codePool>
            <depends>
                 <!-- Ctrl + Space opens autocompletion with all the installed modules... -->
                <Mage_Newsletter />
            </depends>
        </Company_Module>
    </modules>
</config>
```

if you type `Mage`, then there are no suggestions, `mage` is found, so there is somehow a case problem?

**Comment by enriquepiatti** [comment]
Hi @Schrank, what do you mean with Mage and mage? it works for me with both cases:
![depends_autocomplete](https://f.cloud.github.com/assets/1512470/2215112/8229af58-99e6-11e3-8506-d0f1c8411b81.png)

**Comment by Schrank** [comment]
This. Will test again and report back

Von unterwegs gesendet

**Comment by Schrank** [comment]
Tried it again, even magicento cache deletion doesn't help.

But if it only my problem
![broken_autocompletion](https://f.cloud.github.com/assets/379680/2241315/9d89dbba-9cca-11e3-900c-baf59eb534c1.png)

But maybe it is the EAP version?
![phpstorm_version](https://f.cloud.github.com/assets/379680/2241318/bea1d62c-9cca-11e3-8767-263e94dcf6c0.png)

**Comment by enriquepiatti** [comment]
hmmm... weird but could be, why are you using that EAP anyway? there is a stable release newer than that (I'm using 133.803 for example, and the last EAP is 133.925).
Anyway, is your project different in someway? (I don't know you are using modman, or you have the core code from Magento in another folder etc).
Is this happening for all your projects?

**Comment by enriquepiatti** [comment]
I can reproduce the bug now, is a config setting from PhpStorm (see image).
The weird thing is that it was working with "m" and not with "M", the reason for that is because the autocomplete value in that case is not Mage_Core but instead: <Mage_Core, then the first letter is "<", if you set the Code Completion type to ALL or NONE then it will work with only "M" on the first case and with "m" and "M" on the second case.
![codecompletioncase](https://f.cloud.github.com/assets/1512470/2366053/7d0faaf4-a6ed-11e3-8def-17b0a131af0c.png)

**Comment by Schrank** [comment]
Every day something new. Thanks for that!
