### ISSUE TITLE
Broken foreach

### ISSUE THREAD

**Issue by ihor-sviziev** [enriquepiatti/Magicento#113]
For tests I created empty class:

``` php
class test {
    /**
     * @param Varien_Data_Collection|Varien_Object[] $items
     */
    protected function test($items)
    {
        foreach ($items as $item) {
            $item->getData('test');
        }
    }
}
```

If Magicento enabled(only after PhpStorm restart) i have next message:
![1](https://f.cloud.github.com/assets/1873745/2292377/15496180-a058-11e3-9029-7e70e6f09548.png)

If Magicento disabled i haven't this issue.

Magicento version 2.6.5
PhpStorm 7.1.3 #PS-133-982

**Comment by enriquepiatti** [comment]
Thanks @igor-svizev, I have fixed it, will be available on the next release.
Note also that PhpStorm can understand "getData" only because you are using "Varien_Object[]" if you use only Varien_Data_Collection or any Collection type etc PhpStorm won't understand the type of "$item", I'm working for a better solution in these cases.

**Comment by ihor-sviziev** [comment]
@enriquepiatti I know about Varien_Data_collection only, thanks for fix. Waiting for next release :+1:
