### ISSUE TITLE
Uploading eval.php file fails

### ISSUE THREAD

**Issue by richdynamix** [enriquepiatti/Magicento#160]
Everytime I try to evaluate the php on the remote server Magicento uploads the eval.php file into the var folder but the shows this message.

```
Magicento Notification: TimeOut trying to upload eval.php to the default Deployment Server. You can set change the timeout limit from Magicento Settings
```

When I try to view the file it's empty. 

When I try to test PHP in the magicento config I get the following 

https://www.dropbox.com/s/ocf24mtkxqlf1pc/Screenshot%202015-04-15%2008.28.01.png?dl=0
https://www.dropbox.com/s/aohwjbael22co5z/Screenshot%202015-04-15%2008.28.15.png?dl=0

No matter what I do it doesn't seem to want to work.

I am running my server inside a VM with vagrant. All other functions are working as expected.

Any help would be great.

Steven

**Comment by enriquepiatti** [comment]
Hi @richdynamix please check my last comment here:
https://github.com/enriquepiatti/Magicento/issues/155#event-278698869
it will explain a bit better how the eval.php works and how can you manage it to make it work with your particular server config.
Sadly I can't code anything inside the deployment part of PhpStorm, I'm doing some type of hack there but it doesn't work in all situations, so I guess you need to do some manual work in your case.

Maybe you can add some delay to the eval.php execution, and uplad it automatically to your server with some external app when it changes, if you have another idea please let me know

**Comment by AreDubya** [comment]
Hi @richdynamix , I had this same issue, and it has been sorted. I should have posted this earlier, my bad. These are my notes, I hope they are helpful:

All Examples from Estate build.

If running with files on remote server, and a minimal set of files locally, use app/Mage.php in phpStorm project dir.

Set Magicento to use phpstormprojects/site/app/mage.php

```
EX: F:/WindowsData/PhpstormProjects/yoursite/app/Mage.php
```

Use HTTP

url to local magento = remote magento

```
EX: http://my.local.ip/myuser/mysite
```

Check upload eval.php automatically

Add user and pass

use var folder 

NOTE : var must be set to accessible.

```
In /etc/apache2/apache2.conf :


<Directory /home/myuser/public_html/mysite/var/magicento>
        Order allow,deny
        Allow from all
</Directory>
```

Make sure ownership and permission are set properly for that folder. 

I feel your frustration, but trust me, getting Magicento working is worth it. And thanks @enriquepiatti  for your pointers in my question.

**Comment by AreDubya** [comment]
Ah, also, make sure your permissions are right on Vagrant. It works.

**Comment by richdynamix** [comment]
@enriquepiatti @AreDubya,

Thanks for you comments and suggestions. Unfortunately its not been straight forward as that for me.

I have been using Magicento for about a year now and its awesome for in IDE functionality however my working setup in the office was limited in the access I had to the server.

I have since switched to Vagrant for a much fast development environment and setup. To give you some background I created a build script similar to Laravel Homestead which is a pre configured Magento ready centOS box with all the tools. I use NFS for mounting the file system as it gives a much faster read/write IO than the built in VirtualBox shared folders.

I have tried setting up the server config in PHPStorm by local, in place & SFTP. All three of these work and still allow for tools such as xdebug to work. My project files sit inside my home directory, one for work and one for personal `/Users/Gizmo/Sites/Work/project`. Vagrant maps this home directory to `/var/websites` on the box which is configured to as Apaches home directory for all sites.

Since I use this mapping, all of my project files are local with instant changes seen in the VM. Even when I set the server setup to use SFTP its basically just pushing the changed files over the VM to the mapped folder, which the folder they are being pushed from so no issues there.

When I try and use the built in PHP Interpreter instead of HTTP method I get the following error. 
https://www.dropbox.com/s/y1rinqqw54kj8jz/Screenshot%202015-04-16%2008.05.37.png?dl=0

It is pretty frustrating but I understand the limitations in the IDE. I use `magerun` often enough to be productive but I would love it if I can do the common tasks like empty cache and template hint switching from the IDE.

@enriquepiatti Magicento truly is my favourite plugin for PHPStorm.

**Comment by richdynamix** [comment]
OK little update here:

I got it working eventually. As I wrote the last comment it came to me I am trying to upload the file rather then leave in place. I disabled the line `Upload eval.php automatically using the default Deployment server config`

PHP now registers fine.

Thanks again for all the help.

**Comment by enriquepiatti** [comment]
Hi @richdynamix yes, exactly, the main idea is just that, you need to "find a way" to put the eval.php created by Magicento in your PhpStorm project folder (.idea/magicento/eval.php by default or var/magicento/eval.php if you use var folder) into your Magento server (local or remote or virtual).

I will try to explain it a bit better because I know those settings are a bit confusing when they don't work automatically:

**There are 3 common situations:**
1) Project folder is local and your Magento server is local too (and in sync with the project folder in PhpStorm)

2) Project folder is local but your Magento server is in a VM (but the code is in sync or mapped automatically to your VM)

3) Project folder is local but your Magento server is remote

**Possible Solutions:**
1) 
Normally if your Magento server is local and you have it in sync with your PhpStorm project folder then everything is automatic (and is working even when you use .idea/magicento/eval.php).

2)
if you use a virtual machine then is automatic in most of the cases too because normally all your local files from your PhpStorm project are mapped automatically to your virtual folder (but in this case you will probably use the var folder, not .idea folder), that means that the eval.php created by Magicento will be available there too automatically. 
(if it executes the eval.php but executes the wrong code, maybe you can try the delay option here, because maybe the eval.php is executed in your Magento server before it changes, that means is executing an old version of the eval.php)

3)
And if you have your Magento server in a remote server, then you will probably find a solution to upload eval.php there, Magicento has an option to try to upload it automatically (if you have configured some deployment server in PhpStorm and is assigned by default in your project), but if this doesn't work, then you can upload it with some external app (you should configure this tool manually) and use the delay setting from Magicento (so Magicento will wait that time before trying to use the eval.php in your remote server).

But the basic idea is the same for all solutions, Magicento will create a file called eval.php (inside .idea folder or inside var folder) and execute that eval.php using HTTP in your Magento server. So you need to make sure that file exists and is accessible via HTTP in your server when Magicento tries to execute it.
