### ISSUE TITLE
New versions of plugin

### ISSUE THREAD

**Issue by Koc** [enriquepiatti/Magicento#187]
Hello!

Is this project still alive? Is there roadmap for new versions?

**Comment by enriquepiatti** [comment]
Hi @Koc yes still alive, but I'm working more on the new plugin for Magento2 because there are not so many pending things for Magento1 in Magicento (if you have an idea that could add a really big difference speeding up the development please let me know, or use the "uservoice" from magicento.com).
Anyway, I'm testing some solutions to improve the debug process in Magento and also some ideas to make it more collaborative, Follow @magicentoplugin in twitter, I will post the updates there
