### ISSUE TITLE
[Magento2] Allow jump to original/overriden layout/template

### ISSUE THREAD

**Issue by Koc** [enriquepiatti/Magicento#216]
For example I've overrided layout `Magento_Catalog/category_view.xml` in theme `Vendor_theme`. It would be nice add linemarker for jumping to original layout file from my overriden. And vice versa: show overriden layout files in original. Similar to class inheritance

**Comment by Koc** [comment]
please add this feature

**Comment by enriquepiatti** [comment]
@Koc try downloading Magicento2 and installing it again, this feature should be available in 1.5+ (read the changelog to know how to use it)

**Comment by Koc** [comment]
@enriquepiatti how can I download it again? I've forgot my download link. Can you resend it to my email? (koc-dp@yandex.ru). It would be nice add form on the site where users can enter own email and got actual download link.

**Comment by enriquepiatti** [comment]
@Koc I have sent you the link
But I recommend to save the link somewhere, should be also in your email, you can mark that in your inbox and you can search for that. Also the download link is always: http://www.magicento.com/rest/plugin/download?key=[YOUR KEY HERE]. But you don't need that either, if you have Magicento2 already installed it will give you a notification about a new version and you will get the link there (and also there is a button "update" in Magicento2 settings), this didn't happen in this case because I didn't release it officially, just a new temporary update so you can start using and testing these features.

**Comment by Koc** [comment]
@enriquepiatti  thank you. Changelog looks like not updated on site http://easycaptures.com/fs/uploaded/1045/9948011904.png

Can you create linemarker instead of action in next version? It would be much semantic (like class inheritance).

**Comment by enriquepiatti** [comment]
changelog is in your plugin description, will be updated with the official release in some days.
Regarding to the linemarker I think it will consume more resources I guess, I need to test it. 
And take into account linemarker will be only on the top of the file, you can see faster right now just using ALT+M everywhere on the file if it has an override or not, and jump to it, all with the keyboard no need to scroll with your mouse and click it etc
