### ISSUE TITLE
[Magento2] Use native remote interpreter

### ISSUE THREAD

**Issue by Koc** [enriquepiatti/Magicento#222]
I've tryed using some actions like toggle template hints and clear cache. It doesnt work on my env. I have:

* remote project deployed by sftp, see settings https://yadi.sk/i/D4siRXt535qtVi
* configured remote interpreter used for this project https://yadi.sk/i/UmxqLybR35qtih
* Apache with document root `DocumentRoot /home/dev/vhosts/my-super-site.dev/pub` (**pub** folder is document root)

1. I've tryed using just php interpreter - it doesn't works - Magicento tryes execute my local php, not remote
2. then try use http - it also doesn't work because of pub folder. 
3. changed document root in Apache vhosts, but it also doesn't work because new created file aren't uploaded. It uploaded only on next saving of any file (see settings of remote project, but it is impossible to change this settings).

Also executing Magento command using local php, not remote or http call.

So proposal is use native remote interpreter https://confluence.jetbrains.com/display/PhpStorm/Working+with+Remote+PHP+Interpreters+in+PhpStorm

**Comment by Koc** [comment]
https://blog.jetbrains.com/phpstorm/2015/07/remote-tools-via-remote-php-interpreters-in-phpstorm-9/

**Comment by enriquepiatti** [comment]
Hi @Koc yes I'm aware of that, is in TODO list, but you should be able to use the HTTP (not for commands) at least, is a bit more difficult in your case, because you need to configure some external software (if PhpStorm is not doing correctly) to upload the file generated by Magicento2 to your server.
This is how PHP features works:
1) Magicento creates an eval.php file
2) Magicento saves it in .idea/magicento2/ or in /pub/magicento2/ folder (you need to choose to save it in pub folder)
3) Magicento executes that eval.php using HTTP as any other request

The problem (if I understand you) is that the eval.php file is created in your local pub folder but not uploaded to your remote server.
You can install some software to sync pub/magicento2/ folder automatically with your remote server, and also configure a "delay" in Magicento2 settigs (to give it some time to the sync before Magicento tries to execute the eval file).
Try also checking if the eval.php file is created correctly in your remote server and if it's accessible via HTTP (just use your browser to access to that file)

Let me know if that helps, I will work on the remote interpreter anyway too.

**Comment by Koc** [comment]
Hello and thank you for answer.

> The problem (if I understand you) is that the eval.php file is created in your local pub folder but not uploaded to your remote server.

yes, you are correct, it uploaded only when I am saving any file. So as woraround currently I am using next: alt+m, flush cache, got error, save any file (eval.php uploaded), alt+m, flush cache (again), got error about timeout :) (yes, it is possible increase timeout). So current implementation is useless for my env. It easier execute native console command via putty.

Will wait for remote interpreter.

**Comment by enriquepiatti** [comment]
@Koc What is the error about timeout? do you mean that eval.php is executed correctly but is taking too long and you are receiveing a php timeout error on that script?
(try also accessing that eval.php using your browser, you can even debug that file, or edit it manually using PhpStorm as any other PHP file...)

**Comment by enriquepiatti** [comment]
Native PHP Interpreter is ready to use now with Execute Magento2 Command Action (v1.2.0)
To allow PHP features I recommend to use HTTP option, and if it's too hard to sync the created eval*.php (now Magicento creates a different eval for every action) then you can generate them (just try executing the action, it won't works the first time because the eval*.php file is not in your server) and upload the eval*.php files manually to your server, so the next time you try executing the action with HTTP the file will be there and executed. Check Magicento2 settings for more info. 
Could be a bit tricky depending on your environment but the concept is really simple, is just a normal php file executed via HTTP (you can even modify it manually and debug it with your browser).
