### ISSUE TITLE
Magicento 2 Eval.php upload in PHPStorm creation / upload issues. 

### ISSUE THREAD

**Issue by AreDubya** [enriquepiatti/Magicento#226]
Hi Enrique,

I am having an issue with Magicento 2 eval.php sync. It's taken several forms.

Setup: PHPStorm 2016.3 on Windows 10. Project files local, with a Vagrant VM setup as an SFTP remote server. Automatic uploads always, watching external changes. Set to use http, put eval in pub/magicento2 folder. Magicento 2 version 1.2.0.

When I have remove eval.php and multiple eval.php unchecked, the file is never uploaded. If it is, it seems to be because of interaction with another file. The changes in file time and content aren't noticed by PHPStorm.

When I have remove eval.php checked and multiple eval.php unchecked, the file is never created (in the host Win10 file system). The delete command sometimes shows up a minute or two later in the File Transfer panel.

When I have remove eval.php checked and multiple eval.php checked, the file is never created (in the host Win10 file system). Haven't seen any deletes go through the log yet.

When I have remove eval.php checked and multiple eval.php checked, the file is never created (in the host Win10 file system). Haven't seen any deletes go through the log yet.

When I have remove eval.php unchecked and multiple eval.php checked, the file is never uploaded(in the host Win10 file system). Again, sometimes a minute later or so it will upload randomly, right after an interaction with another file (not save).

I never had (and still don't have) this issue with Magicento 1. What would cause this for Magicento 2? 

Also, for a remote server, what should I have set for "Absolute Path to php interpreter" and Path to bin/magento?

Thanks!

**Comment by AreDubya** [comment]
As a PS, I've reached out to JetBrains to see what they have to say about the first scenario - in that case the file is created reliably, but never noticed for uploading.

**Comment by enriquepiatti** [comment]
Hi @AreDubya I think this should work for you:
1) uncheck remove eval.php
2) check use multiple eval.php (this will generate not eval.php but "eval*.php" files different for every action)
3) make sure the new eval*.php files are created
4) upload them manually (you can also edit them before if you want for some reason)
5) execute the actions again, it doesn't matter if the files are not uploaded again, because the files are already in your server and that is what Magicento executes, with HTTP

If the action is not working for some reason just use your browser to make sure the eval*.php files are accessible, and they are not throwing errors

**Comment by AreDubya** [comment]
Hey @enriquepiatti , 

I had thought of that, but I'm so used to the eval.php shooting onto local instantly the thought of going manual was hard to swallow. Still, it'll do until jetbrains sort out the file watching. 

Totally unrelated to this issue, but if you don't mind what the proper settings are for Absolute Path to php interpreter" and Path to bin/magento when using a remote server / interpreter?

Thanks

**Comment by enriquepiatti** [comment]
Don't worry about those settings if you are using HTTP.
Those things are used for example if you want to execute Magento2 commands throught Magicento2 (ALT+M > Execute Magento2 Command). But you can set that there too
But In your case, because you are running Magento2 in VM then you probably need to setup a PHP Remote Interpreter in PhpStorm, and then inside the dialog to execute Magento2 commands you can choose that PHP Interpreter to run the command in your VM

**Comment by AreDubya** [comment]
Awesome Enrique, and thanks for another great plugin.
