### ISSUE TITLE
How to download version 2 of Magicento?

### ISSUE THREAD

**Issue by luke-denton-aligent** [enriquepiatti/Magicento#231]
I was provided a link at my workplace to a version of Magicento 1 and was told that to download version 2, all I have to do is append `&v=2` to the end of the URL. I tried that, and also tried editing the HTML on the page so that the link on the page has the same addition to the URL, but both times I still got version 1 of Magicento.

How do I download version 2?

**Comment by enriquepiatti** [comment]
Hi @luke-denton, this is only for posting issues with the plugins, but anyway, Magicento2 is a different product, you need to buy a license for it, the reason why it was available free with "v=2" parameter before is because it was a beta version, now it has a stable release, please go to www.magicento.com for more info
