### ISSUE TITLE
Remote project problems

### ISSUE THREAD

**Issue by z1haze** [enriquepiatti/Magicento#232]
I have this plugin installed and configured with a remote project, so I have upload the eval_null.php to the pub/magicento2 folder.

I had created a module then deleted it.. Now when I go into the magicento context menu to create a new module by that same name of the one I delted, it tells me it already exists..  What is going on with this?

I also cannot execute the clear magento cache command through the plugin it tells me its searching for some file pub/magicento2/eval_cleanmagento2cache.php which doesnt exist either. Please provide a solution to this.

**Comment by z1haze** [comment]
I also was not aware that I would not be able to come back and find the download link again so now I dont have that either.

**Comment by enriquepiatti** [comment]
Hi @z1haze, clear Magento2 cache is to clear the cache in your Magento2, not Magicento2. To clear Magicento2 cache please use "Refresh Magicento2 Indexes" if that does not work try using File > Invalidate Cache Restart.

If you are having problems with the PHP features, since you are using a remote server it could be due to some problem with the settings, I can help you with that but please send me an email with a screenshot showing your Magicento2 settings.

Lastly, if you lost the private link please contact me by email

**Comment by z1haze** [comment]
What is your email?

**Comment by z1haze** [comment]
Hi, please give me your email. Your plugin is not working correctly, and I need to send you this screenshot. Also the suggestions you gave for fixing the magicento caching of deleted modules did not fix either. thanks.

**Comment by enriquepiatti** [comment]
@z1haze my email is in magicento.com: contacto@enriquepiatti.com

**Comment by z1haze** [comment]
Please note this screenshot: http://img.stephenhendricks.me/phpstorm64_2017-02-27_08-50-24.png the Module TradeGlobalDevelopment_TGCommerce no longer exists, but no matter what I do, following your instructions earlier, it never goes away.

**Comment by z1haze** [comment]
Here are my settings: http://img.stephenhendricks.me/phpstorm64_2017-02-27_08-55-33.png

**Comment by enriquepiatti** [comment]
@z1haze are you sure the module TradeGlobalDevelopment_TGCommerce was correctly removed from your /app/etc/config.php file?
