### ISSUE TITLE
[Magento2] Generate plugin produces wrong syntax code

### ISSUE THREAD

**Issue by Koc** [enriquepiatti/Magicento#245]
I've tryed to generate plugin and got new class

```php
<?php

namespace Brouzie\Satin\Plugin\Model\Layer\Filter;

class AttributePlugin
{


    public function aroundGetItems(\Smile\ElasticsuiteCatalog\Model\Layer\Filter\Attribute $subject, \Closure $procede}
```

it has syntax errors

**Comment by Koc** [comment]
Also it asks for scope - but does scopes affects plugins?

**Comment by enriquepiatti** [comment]
Thanks @Koc I have corrected the typo, also changed to callable instead of Closure, will be available in next release
Regarding to the area, is not needed, but you can use it, please read for more info:
http://devdocs.magento.com/guides/v2.1/extension-dev-guide/plugins.html#configuration-inheritance

**Comment by Koc** [comment]
want write about callable also but you fix it faster :) thank you

**Comment by enriquepiatti** [comment]
Not sure what was the problem here, but please test if the issue continue after updating to v.1.7.0 and reopen in that case. 
Thanks !
