### ISSUE TITLE
Auto completion for events should be namespace_module/observer

### ISSUE THREAD

**Issue by Schrank** [enriquepiatti/Magicento#44]
To allow rewrites of observers, the classname should not be absolute `Namespace_Module_Model_Observer`, instead is should be resolvable: `namespace_module/observer`

It would be awesome if magicento makes a lookup into the `config/global/models` node for the child. But I think for 90% of the cases it is enough to use the auto completion inside this node.

**Comment by enriquepiatti** [comment]
Personally I think observers should not be rewritten, normally if you encounter that situation, then that's because only just one event, so it's better to disable the original event, and just define a new one (I think is clear to see what's happening just seeing the XML). Anyway, I don't see any big disadvantage using the factory instead of the class name so I will change it in the next release.

**Comment by Schrank** [comment]
Good argument, never thought that way, but you are right :-) :+1: But you are right with the change too, this way it is easier, if other people think in other ways.

And btw a big thank you from the whole berlin developer community. We had a meeting today and when I told them, that you had a paypal donate button, we all agreed, that working with magicento makes us all a lot more productive!

**Comment by enriquepiatti** [comment]
Done in v1.6.0
