### ISSUE TITLE
[critical] .modman causes problem during start up?

### ISSUE THREAD

**Issue by amenk** [enriquepiatti/Magicento#57]
Do you use modman?

I just did an modman init, cloned https://github.com/LimeSoda/LimeSoda_SampleDataGenerator and a modman deploy (which creates the symlink) and this does not allow loading of PHPstorm anymore.

There is a huuuuge exception and I think it is happening during the PHP parsing.

Can you test this or shall I provide you with more debug data?

**Comment by amenk** [comment]
okay - can't reproduce it at the moment. reinstalled the module and phpstorm starts.

**Comment by enriquepiatti** [comment]
This problem must be related with:  
https://github.com/enriquepiatti/Magicento/issues/54  
Right now I don't know how to solve this, I think is a bug in PHPStorm (it's happening with the symfony plugin too).  
I can only think in one solution at the moment: to make optional the automatic factory and block type recognition, so if that's giving you problems you can at least use the rest of the features (to me everything is working fine, I couldn't reproduce the error since 1.7.1 release)
