### ISSUE TITLE
Copy class to local code pool

### ISSUE THREAD

**Issue by amenk** [enriquepiatti/Magicento#62]
What do you think about adding a function to copy classes to the local code pool?

I know - that's bad - but in some cases it isn't.

There are some cases of local patches which are clearly valid to be put in local, and where a class rewrite or event is not suitable.

I do not know if we should put a warning - but that might not be the scope of the extension.

**Comment by enriquepiatti** [comment]
I think those cases are not so common, and if you need it, it's really really easy to do it manually.

**Comment by enriquepiatti** [comment]
I've added a php script doing exactly this, just to show the new feature included in Magicento v2.0.0, you can download the script and execute it with Magicento, more info here:
http://magicento.com/#magicento-php-scripts

**Comment by amenk** [comment]
awesome ... one thing: that PHP script does not sync the file system - so the new file would not appear in "Changes" tab of PHPstorm.

**Comment by enriquepiatti** [comment]
yes, that part is difficult to do because the script is creating a file using PHP not the IDE, so you need to add to the VCS yourself later (and sometimes refresh the file system to see it in PHPStorm)
I was thinking in some options for solving this type of problems, that is, to provide some type of access to the IDE code and functionalities directly from PHP. But I have not tested them yet.

**Comment by amenk** [comment]
But when executing external tools in PHPStorm I believe there is also an option to do a filesystem refresh afterwards? Maybe that same thing could be used here?

**Comment by enriquepiatti** [comment]
yes but happens if you have a script which doesn't require any filesystem refresh? for example, the current actions for toggling template hints or clearing the cache etc can be implemented with a php script too (at really they are php script created by Magicento), and they don't require to refresh the FS (even more, they could be remote php scripts executed somewhere else).
Maybe we could assume that if the user selects "Force execution with PHP Interpreter" then that is because he want to make some modification to some file in his current project, and hence we could do a FS refresh in that case.
Anyway, I think nobody is using this feature yet so I don't know if it's a good idea to put so much effort here :(

**Comment by amenk** [comment]
Can't there be some flag in the script (/*\* REFRESH FILESYSTEM */ annotation maybe?) to trigger that?
Actually you are building some kind of PHPStormPlugin->PHP Bridge ? Might make even sense as an additional plugin for non magento users?

**Comment by enriquepiatti** [comment]
Yes that is the type of interaction I said should be developed for a better integration, it could be with comments in the code or parsing the result of the script (for example it culd be an XML acting as some type of RPC betweem the script and the PHPStorm, etc).

It's true this "bridge" could be useful for some people trying to extend the ide for doing some simple tasks without writing a plugin in Java from zero.
The problem is that PHP scripts are really slow compared to doing the same directly on the IDE.
But for example for Magento you need sometimes to do it with PHP, because you need to read something from the DB, or to do something with the DB (refreshing the cache, template hints, resetting the installer script, etc).
Anyway, if people find this useful there are a lot of things to do in this field.
