### ISSUE TITLE
Choose if Magicento shall reformat XML nodes

### ISSUE THREAD

**Issue by tim-bezhashvyly** [enriquepiatti/Magicento#75]
i'm always writing <action/> nodes in one row like:

<action method="setIsHandle"><applied>1</applied></action>

however when i'm using Magicento autocompletion it is automatically re-formatting all such nodes to something like this:

<action method="setIsHandle">
    <applied>1</applied>
</action>

if i'm using default phpStorm autocompletion this doesn't happen.

i guess there is not setting which can disable such kind of re-formatting in Magicento? Is it possible to add one?

**Comment by enriquepiatti** [comment]
That must be changed in your XML code style:
http://magicento.com/assets/img/features/xml-format-do-not-wrap.png
You should have that setting in all your projects is MUCH safer (even if you don't use Magicento) because how you probably now Magento doesn't work well with those wrapping texts.
Magicento will check periodically your config.xml searching malformed nodes and will warning you about that, but anyway, it's much better to have the correct code style in your project.

**Comment by tim-bezhashvyly** [comment]
strange, i already got it set up like this, still xml is reformatted on Magicento autocompletion. On standard phpStorm autocompletion code is not reformatted.

**Comment by enriquepiatti** [comment]
I can't see your examples, please could you attach some images of your XML code style settings and also the missing examples from your first post?

**Comment by Ian410** [comment]
I can confirm this happens on mine as well, when typing out an action in a layout xml, if you tab on a Magicento action it auto formats it.

Selecting it:
![image](https://f.cloud.github.com/assets/1384254/843634/e346c3d6-f3c2-11e2-9634-ed384adeee79.png)

Result:
![image](https://f.cloud.github.com/assets/1384254/843639/00fabdec-f3c3-11e2-8e82-efddf89bd29c.png)

**Comment by tim-bezhashvyly** [comment]
Confirming. Issue is fixed in version 2.4.0.

**Comment by shawesome** [comment]
I'm seeing this issue in Magicento 2.9.1

My XML code style settings: https://up.kibakoapp.com/NxSbWc5tDD

Before: https://up.kibakoapp.com/QL4OAHKkbY
After: https://up.kibakoapp.com/JFCgDt1Ehm (you can see file changes noted on the left hand side)
