### ISSUE TITLE
Module is not recognized when using mage instead of Mage

### ISSUE THREAD

**Issue by weiners** [enriquepiatti/Magicento#79]
Hi,

When using capital M for Mage, Magicento recognize the module but not with m
For exmaple mage::getModel('googlecheckout/api')->processCallback() will not recognize processCallback.

Cheers,
Shay

**Comment by enriquepiatti** [comment]
Why are you typing mage instead of Mage? I think this is one of the ugliest part of PHP, we should avoid that mess and use always the correct case (more in frameworks like Magento which are very dependent on the cases in many places)

**Comment by enriquepiatti** [comment]
Closing because I think is a bad practice to abuse of non case sensitivity from PHP here

**Comment by LPAlex** [comment]
I'd like to draw your attention on that again. I have quite a few community modules that have this kind of call "mage::helper".

I agree with you that it is bad practice but it would help greatly when working with external (badly coded) modules. Why not supporting it and putting just a warning on it?

**Comment by enriquepiatti** [comment]
I'm not so sure about that, I think it could impact on the performance too, because I need to search for Mage:: and mage:: maybe PhpStorm can handle it efficiently anyway, but I'm not sure, and I really hate that practice, what I would do in that case is to refactor all the code, even if it's a community, and if it's open source I would suggest to make a PR with the change.
